site_name: 大观散人
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: 仿宋
  palette:
    # Toggle light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
nav:
- 主页: index.md
- 数值分析: 
  - 数值分析笔记: NA-Notes.md
- 计算机视觉:
  - 复习提纲全解: CV-Notes.md